Kritunga/urls.py
from django.contrib import admin
#Application urls
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/',include('testapp.urls')),

]

testapp/urls.py
from . import views
from django.urls import path
# ADD APP NAME IN URLS
app_name='testapp'

urlpatterns = [
    path('category',views.category_view),# CATEGORY API VIEW URL
    path('orderitem',views.orderitem_view),# ORDERITEM API VIEW URL
    path('login',views.login_view,name='login'),# CUSTOM USER LOGIN  PAGE VIEW URL
    path("logout", views.logout_view, name="logout"),
    path('chef',views.chef_view,name='chef'),# CHEF LIST VIEW PAGE URL
    path('details/<int:id>/', views.chefdetailsview,name='details'),# CHEF DETAILS PAGE URL
    path('pending-alloc-status/<str:id>/<str:chef_id>/',  views.PendingAllocStatus, name = 'pending-alloc-status'),# ALLOCATIONS PENDING STATUS URL
    path('complete-alloc-status/<str:id>/<str:chef_id>/',  views.CompleteAllocStatus, name = 'complete-alloc-status'), # ALLOCATION COMPLETE STATUS URL
    
   
]

testapp/models.py
from unicodedata import category
from django.db import models

# Create your models here.

#########################################################
############### allocation choices #####################
#########################################################

allocation_choices = (
    ('incomplete', 'incomplete'),
    ('pending', 'pending'),
    ('complete', 'complete')
)

####################################################
############## ORDER ITEM MODEL ###################
####################################################

class OrderItem(models.Model):
    order_id=models.CharField(max_length=30,null=True,blank=True)
    category_id=models.IntegerField()
    category_name=models.CharField(max_length=100)
    product_id=models.IntegerField()
    product_name=models.CharField(max_length=100)
    quantity=models.IntegerField()
    price=models.DecimalField(max_digits=20,decimal_places=2)
    description=models.TextField(null=True,blank=True)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    allocation=models.BooleanField(default=False)
    table_no=models.IntegerField()
    prepared_by=models.CharField(max_length=100,blank=True,null=True)
    status=models.CharField(max_length=20, choices=allocation_choices, default='incomplete')


    class Meta:
        verbose_name='OrderItem'
        verbose_name_plural='OrderItems'

    def __str__(self):
        return '{}' .format(self.category_name)


#############################################################
################# CATEGORY MODEL ############################
#############################################################

class Category(models.Model):
    category_id=models.IntegerField()
    category_name=models.CharField(max_length=100)
    description=models.TextField(null=True,blank=True)
    category_image=models.ImageField(default='media')

    class Meta:
        verbose_name='Category'
        verbose_name_plural='Categorys'
    
    def __str__(self):
        return '{}' .format(self.category_name)

#############################################################
############### CHEF MODEL ##################################
#############################################################


class Chef(models.Model):
    chef_id=models.IntegerField()
    chef_name=models.CharField(max_length=100,unique=True)
    chef_image=models.ImageField(default='media')
    category_name=models.ManyToManyField(Category)
    product_name=models.CharField(max_length=100)
    orders_completed=models.IntegerField(default=0)
    description=models.TextField(null=True,blank=True)

    mobile=models.CharField(max_length=100)
    status=models.BooleanField(default=True)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name='Chef'
        verbose_name_plural='Chefs'
    
    def __str__(self):
        return '{}' .format(self.chef_name)

##########################################################
################ CUSTOM USER MODEL #######################
##########################################################

class CustomUser(models.Model):
    username=models.CharField(max_length=100)
    email=models.EmailField()
    password=models.CharField(max_length=30)

    class Meta:
        verbose_name='CustomUser'
        verbose_name_plural='CustomUsers'
    
    def __str__(self):
        return '{}' .format(self.username)

testapp/forms.py
from django import forms
from django.core import validators

class CustomUserForm(forms.Form):
    username=forms.CharField(max_length=30)
    password=forms.CharField(widget=forms.PasswordInput)

    # def clean_username(self):
    #     username = self.cleaned_data['username']
    #     if username != 'admin':
    #         raise forms.ValidationError("invalid username")
    #     return username
    # def clean_password(self):
    #     password = self.cleaned_data['password']
    #     if password != 'admin123':
    #         raise forms.ValidationError("invalid password...pls try again!!!")
    #     return password

testapp/views.py
from unicodedata import category
from .models import CustomUser,Chef,OrderItem
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.shortcuts import redirect, render,get_object_or_404
from .serializers import OrderItemsSerializer,CategorysSerializer
from django.contrib.auth import login, logout, authenticate
from .forms import CustomUserForm
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
import threading
import datetime

#refresh using time,automatically orders completed will zero using the time
def test():
    satisfied=1
    while True:
        current_time = datetime.datetime.now()
        if (current_time.hour==4 ) or (current_time.hour==14):
            if satisfied==1:
                chef=Chef.objects.all()
                for x in chef:
                    x.orders_completed=0
                    x.save()
                satisfied=0
        else:
            satisfied=1

threading.Thread(target=test).start()

# Create your views here.

# we can get orderitem from apis ,this is orderitem api views
@api_view(['POST'])
def orderitem_view(request):
    serializer = OrderItemsSerializer(data = request.data)
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data)
    else:
        return Response(serializer.errors)

# we can get category from apis ,this is category api views
@api_view(['POST'])
def category_view(request):
    serializer = CategorysSerializer(data = request.data)
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data)
    else:
        return Response(serializer.errors)



#login view
@csrf_exempt
def login_view(request):
    form = CustomUserForm(request.POST or None)
    msg = None
    if request.method == "POST":
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                user.save()
                return redirect("testapp:chef")
            else:
                msg = 'Invalid credentials'
        else:
            msg = 'Error validating the form'
    return render(request, "testapp/login.html", {"form": form, "msg": msg})


#order item allocation and chefs list
def chef_view(request):
    #filter the all  orderitems and store in order_list
    orders_list=OrderItem.objects.filter(prepared_by=None) 
    # get all chefs from Chef model using status is active by using filter
    chef_list=Chef.objects.filter(status=True)    
    def chefallotment(st):
        b2=Chef.objects.filter(id=st)
        return b2[0].orders_completed
    try:
        #each orderitem in order list 
        for i in orders_list:
            #we can get orderitem orderid      
            oID=i.order_id
            # orderitem productname
            prn=i.product_name
            # all active chefs store in z 
            z=Chef.objects.filter(status=True)
            zk=[]
            for k in range(len(z)):
                all_user_categories = z[k].category_name.all() #filter chefs who can cook category name items
                filtered_user_categories = z[k].category_name.filter(category_name = i)
                if len(filtered_user_categories)>0:
                    zk.append(z[k])
            z=zk
            print('final z',z)
            print('Im printing z',z)
            #here we get chefs id  
            zc1=[zc.id for zc in z]      
            z=zc1      
            print('Im printing z id',z)
            cn=i.category_name        
            FL=[chefallotment(st) for st in z]  
            m=min(FL)
            i=FL.index(m) 
            asgn=Chef.objects.filter(id=z[i])   
            CN=asgn[0].chef_name
            #get orderid and category name and product_name from orderitem model
            cf=OrderItem.objects.get(order_id=int(oID),category_name=cn,product_name=prn)
            cf.prepared_by=CN
            cf.save()
            cf1=Chef.objects.get(id=z[i])
            #increment to 1 to the particular chef
            cf1.orders_completed=int(cf1.orders_completed)+1
            cf1.save()
        return render(request,'testapp/chef.html',{"chef_list":chef_list})
    except Exception as e:
        print(e)
        return render(request,'testapp/chef.html',{"chef_list":chef_list})

#chef details view and orders allocation to the chef 
def chefdetailsview(request,id):
    chef=Chef.objects.get(id=id)
    print(chef.chef_name)
    orderitem=OrderItem.objects.filter(Q(prepared_by = chef.chef_name) & ( Q(status = 'incomplete') | Q(status = 'pending')))
    if len(orderitem) == 1:
        alloc_1 = orderitem[0]
        return render(request, 'testapp/chef_detail.html', {
                                                        'chef' : chef, 
                                                        'orderitem':  orderitem, 
                                                        'alloc_1' : alloc_1,
                                                        })

    elif len(orderitem) > 1:
        alloc_1 = orderitem[0]
        alloc_2 = orderitem[1:]

        return render(request, 'testapp/chef_detail.html', {
                                                'chef' : chef, 
                                                'orderitem':  orderitem, 
                                                'alloc_1' : alloc_1,
                                                'alloc_2' : alloc_2, 
                                                })
    else:
        return render(request, 'testapp/chef_detail.html', {
                                                'chef' : chef, 
                                                'orderitem':  orderitem, 
 
 
                                                })




# PENDING ALLOCATION  STATUS VIEW
@login_required(login_url='login')
def PendingAllocStatus(request, id, chef_id):
    allocation = OrderItem.objects.get(id = id)
    allocation.status = 'pending'
    allocation.save()
    chef = Chef.objects.get(id = chef_id)    
    return redirect('testapp:details', chef.id)


# ALLOCATION COMPLETED VIEW
@login_required(login_url='login')
def CompleteAllocStatus(request, id, chef_id):
    allocation = OrderItem.objects.get(id = id)
    allocation.status = 'complete'
    allocation.save()
    chef = Chef.objects.get(id = chef_id)  
    return redirect('testapp:details', chef.id)


def logout_view(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("testapp:login")

testapp/templates/testapp/chef.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/chef.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>chefs list page</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="chef">Vistan NextGen</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="chef">Home <span class="sr-only">(current)</span></a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="login">Logout </a>
            </li>&nbsp;
          </ul>
        </div>
      </nav>
    <section class="fruits_section layout_padding">
        <div class="container" >
            <div class="heading_container heading_center " align="center">
                CHEFS LISTS
                </div>
                    <div class="row">
                        {% comment %} here we can get chefs list  from chef model by using context chef_list {% endcomment %}
                        {% for i in chef_list %}
                         <div class="col-sm-2">
                            <div class="card"> 
                                <div>
                                    <img src="{% static i.chef_image.url %}" alt="oops" style = "width:100%; height: auto; margin:auto;" >
                                    <div class="container" align="center">
                                     <a class="btn  btn-success" href="{% url 'testapp:details' i.id %}" <b>{{i.chef_name}}</b></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}                 
                    </div>
                </div>
            </div>
        </div>

    </section>
<div class='jumbotron'>
    <footer id="footer">   
        <div class="container d-md-flex py-4" >
          <div class="container" align="left">
            <div class="copyright">
              &copy; 2021 &nbsp;<strong><span> Vistan Nextgen Pvt Ltd</span></strong>. All Rights Reserved
            </div>    
          </div>
          <div class="container" align="right">
            <a href="https://twitter.com/nextgenvistan" class="twitter"><i class="fa fa-twitter"></i></a>
            <a href="https://www.facebook.com/vistannextgen1/" class="facebook"><i class="fa fa-facebook"></i></a>
            <a href="https://www.instagram.com/vistannextgen/" class="instagram"><i class="fa fa-instagram"></i></a>
            <a href="https://in.linkedin.com/company/vistannextgen" class="linkedin"><i class="fa fa-linkedin"></i></a>
          </div>
        </div>  
      </footer>
    </div>
</body>
</html>

testapp/templates/testapp/chef_detail.html
 
<!DOCTYPE html>
<html lang="en">
  {% load static %}
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/chef_detail.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <title>chef details</title>
</head>
<body>


    <div class="card card-warning">
        <div class="card-header" align="center">
            <h4>Orders | {{chef}}</h4>
            <div class="card-header-action"><br></div>
        </div>

        <div class="table-responsive">
            <div class="card-body p-0">
                {% if orderitem %}                
                    <table class="table table-striped" id = "myTable">
                        <tr>
                            <th class="text-center" onclick="sortTable(0)">Order ID&nbsp;<i class="fas fa-sort"></i></th>
                            <th onclick="sortTable(1)">Category Name&nbsp;<i class="fas fa-sort"></i></th>
                            <th>Product Name</th>
                            <th>Quantity</th>
                            <th>Table No</th>
                            <th onclick="sortTable(4)">Status&nbsp;<i class="fas fa-sort"></i></th>               
                            <th>Action</th>
                        </tr>

                        {% comment %} if chef having only one orderitem this will be executde {% endcomment %}
                        <tr>
                            <td class="p-0 text-center">{{alloc_1.id}} </td>
                            <td>{{alloc_1.category_name|title}}</td>
                            <td>{{alloc_1.product_name|title}}</td>
                            <td>{{alloc_1.quantity}}</td>
                            <td>{{alloc_1.table_no}}</td>
                            <td>
                                {% ifequal alloc_1.status 'pending'%}
                                    <div class="badge badge-warning">{{alloc_1.status}}</div>
                                {% else %}
                                    <div class="badge badge-danger">{{alloc_1.status}}</div>
                                {% endifequal %}

                            </td>
                            <td>
                                {% ifequal alloc_1.status 'incomplete' %}
                                    <a  class="btn btn-md btn-primary" 
                                        style="text-decoration: none;" 
                                        href="{% url 'testapp:pending-alloc-status' alloc_1.id  chef.id%}"
                                        data-toggle="tooltip" data-placement="top"
                                        title="start">
                                        start
                                    </a>&nbsp;
                                    
                                {% endifequal %}


                                                        
                                {% ifequal alloc_1.status 'pending' %}
                                
                                    <a  class="btn btn-md btn-info" 
                                        style="text-decoration: none;" 
                                        href="{% url 'testapp:complete-alloc-status' alloc_1.id chef.id %}"
                                        data-toggle="tooltip" data-placement="top"
                                        title="complete">
                                        Complete
                                        <!-- <i class="fas fa-pen"></i>  -->
                                    </a>&nbsp;  
                                {% endifequal %}

                            </td>
                        </tr> 
                        {% comment %} if chef having morethan one orderitem this will be executde and in this orderitem first order is enabled and 
                        from second order onwards buttun will be disabled {% endcomment %}
                        
                        {% for alloc in alloc_2 %}
                            <tr>
                                <td class="p-0 text-center">{{alloc.id}} </td>
                                <td>{{alloc.category_name|title}}</td>
                                <td>{{alloc.product_name|title}}</td>
                                <td>{{alloc.quantity}}</td>
                                <td>{{alloc.table_no}}</td>
                                <td>
                                    {% ifequal alloc.status 'pending'%}
                                        <div class="badge badge-warning">{{alloc.status}}</div>
                                    {% else %}
                                        <div class="badge badge-danger">{{alloc.status}}</div>
                                    {% endifequal %}

                                </td>
                                <td>
                                    {% ifequal alloc.status 'incomplete' %}
                                        <a  class="btn btn-md btn-warning disabled btn-progress" 
                                            style="text-decoration: none;" 
                                            href="{% url 'testapp:pending-alloc-status' alloc.id  chef.id%}"
                                            data-toggle="tooltip" data-placement="top"
                                            title="start">
                                            start
                                        </a>&nbsp;
                                    {% endifequal %}

                                                            
                                    {% ifequal alloc.status 'pending' %}
                                    
                                        <a  class="btn btn-md btn-info disabled btn-progress" 
                                            style="text-decoration: none;" 
                                            href="{% url 'testapp:complete-alloc-status' alloc.id chef.id %}"
                                            data-toggle="tooltip" data-placement="top"
                                            title="complete">
                                            Complete
                                            <!-- <i class="fas fa-pen"></i>  -->
                                        </a>&nbsp;  
                                    {% endifequal %}

                                </td>
                            </tr> 
                        {% endfor %}
                        
                    </table>
                {% else %}
                {% comment %} if chef dont have any orders this else part will execute {% endcomment %}
                <br>
                    <h6 class="text-center" style="color: orangered;">No orders till now ! </h6>   
                <br> 
                {% endif %}
            </div>
        </div>
    

    </div>




    <script>
    function myFunction() {
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        table = document.getElementById("myTable");

        console.log(input, filter, table);
        tr = table.getElementsByTagName("tr");
        for (i = 0; i < tr.length; i++) {
        td = tr[i].getElementsByTagName("td")[1];
        if (td) {
            txtValue = td.textContent || td.innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
            tr[i].style.display = "";
            } else {
            tr[i].style.display = "none";
            }
        }       
        }
    }



    function sortTable(n) {
    var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
    table = document.getElementById("myTable");
    switching = true;  
    dir = "asc"; 
    while (switching) {    
        switching = false;
        rows = table.rows;   
        for (i = 1; i < (rows.length - 1); i++) {
        shouldSwitch = false;
        x = rows[i].getElementsByTagName("TD")[n];
        y = rows[i + 1].getElementsByTagName("TD")[n];
        if (dir == "asc") {
            if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {          
            shouldSwitch = true;
            break;
            }
        } else if (dir == "desc") {
            if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {          
            shouldSwitch = true;
            break;
            }
        }
        }
        if (shouldSwitch) {     
        rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
        switching = true;      
        switchcount ++;
        } else {
        if (switchcount == 0 && dir == "asc") {
            dir = "desc";
            switching = true;
        }
        }
    }
    }
    


    {% if messages %}
        console.log('message')

                iziToast.show({
                                title: 'Hii',
                                message: '{% for i in messages %}{{i}}{%endfor%}',
                                position: 'topRight',
                                color: 'success'
                            });
    {% endif %}

    </script>
  
        <footer id="footer">   
            <div class="container d-md-flex py-4" >
              <div class="container" align="left">
                <div class="copyright">
                  &copy; 2021 &nbsp;<strong><span> Vistan Nextgen Pvt Ltd</span></strong>. All Rights Reserved
                </div>    
              </div>
              <div class="container" align="right">
                <a href="https://twitter.com/nextgenvistan" class="twitter"><i class="fa fa-twitter"></i></a>
                <a href="https://www.facebook.com/vistannextgen1/" class="facebook"><i class="fa fa-facebook"></i></a>
                <a href="https://www.instagram.com/vistannextgen/" class="instagram"><i class="fa fa-instagram"></i></a>
                <a href="https://in.linkedin.com/company/vistannextgen" class="linkedin"><i class="fa fa-linkedin"></i></a>
              </div>
            </div>  
          </footer>
        

</body>
</html>

testapp/templates/testapp/login.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <title>Login page</title>
</head>
<body>
    <section>
  
        <div class="box">
          
          <div class="square" style="--i:0;"></div>
          <div class="square" style="--i:1;"></div>
          <div class="square" style="--i:2;"></div>
          <div class="square" style="--i:3;"></div>
          <div class="square" style="--i:4;"></div>
          <div class="square" style="--i:5;"></div>
          
         <div class="container" align="center"> 
          <div class="form"> 
            <h2>User Login  </h2>
            <form action="" method="post">
                {{form.as_p}}
                {% csrf_token %}
                <br>   
                <input type="submit" name="" value="login">
            </form>
            
          </div>
        </div>
          
        </div>
      </section>
</body>
</html>